stages:
  - prepare
  - checks
  - build
  - test
  - analyze
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: ins-cpp:10

.clang:
  variables:
    CC: clang
    CXX: clang++

.gcc:
  variables:
    CC: gcc
    CXX: g++

.schedule:
  only:
    - schedules

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                      Prepare                                                       ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

check-image:
  stage: prepare
  script:
    - g++ --version
    - clang++ --version
    - clang-tidy --version
    - cmake --version
    - conan --version
    - doxygen --version
    - cppcheck --version
    - lcov --version
    - genhtml --version
    - gcov --version
    - xml_grep --version

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                       Checks                                                       ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

clang-tidy:
  stage: checks
  script:
    - cmake -Bbuild/Release -S. -DCMAKE_BUILD_TYPE=Release -DENABLE_MAIN=ON -DENABLE_GUI=ON -DENABLE_TESTING=OFF -DENABLE_DOXYGEN=OFF -DLOG_LEVEL=TRACE -DWARNINGS_AS_ERRORS=ON -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=ON -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Release --target copy-compile-commands
    - clang-tidy --extra-arg=-Wno-unknown-warning-option $(find src -type f -name "*.cpp")

clang-tidy:tests:
  stage: checks
  script:
    - cmake -Bbuild/Debug -S. -DCMAKE_BUILD_TYPE=Debug -DENABLE_MAIN=OFF -DENABLE_GUI=OFF -DENABLE_TESTING=ON -DENABLE_DOXYGEN=OFF -DLOG_LEVEL=TRACE -DWARNINGS_AS_ERRORS=ON -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=ON -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Debug --target copy-compile-commands
    - clang-tidy --extra-arg=-Wno-unknown-warning-option $(find test -type f -name "*.cpp")

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                  Build Main & GUI                                                  ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

.build:main-gui:
  stage: build
  needs: ["check-image"]
  script:
    - cmake -Bbuild/Release -S. -DCMAKE_BUILD_TYPE=Release -DENABLE_MAIN=ON -DENABLE_GUI=ON -DENABLE_TESTING=OFF -DENABLE_DOXYGEN=OFF -DLOG_LEVEL=TRACE -DWARNINGS_AS_ERRORS=ON -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=OFF -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Release -- -j2

main-gui:clang:
  extends:
    - .build:main-gui
    - .clang

main-gui:gcc:
  extends:
    - .build:main-gui
    - .gcc

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                     Build Tests                                                    ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

.build:tests:
  stage: build
  needs: ["check-image"]
  script:
    - cmake -Bbuild/Debug -S. -DCMAKE_BUILD_TYPE=Debug -DENABLE_MAIN=OFF -DENABLE_GUI=OFF -DENABLE_TESTING=ON -DENABLE_DOXYGEN=OFF -DENABLE_COVERAGE=TRUE -DLOG_LEVEL=TRACE -DWARNINGS_AS_ERRORS=ON -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=OFF -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Debug -- -j2
  artifacts:
    untracked: true
    expire_in: 2h

tests:clang:
  extends:
    - .build:tests
    - .clang

tests:gcc:
  extends:
    - .build:tests
    - .gcc

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                        Test                                                        ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

run-tests:clang:
  stage: test
  needs: ["tests:clang"]
  script:
    - cd build/Debug/test
    - ctest -j2 --output-on-failure
    - xml_grep --pretty_print indented --wrap '' --descr '' --cond "testsuites" *.xml > ../../../junit.xml
    - sed -i ':begin;$!N;s/<\/testsuites>\n<testsuites>//;tbegin;P;D' ../../../junit.xml
  artifacts:
    when: always
    reports:
      junit: junit.xml

run-tests:gcc:
  extends: run-tests:clang
  needs: ["tests:gcc"]
  artifacts:
    untracked: true
    expire_in: 2h

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                      Analyze                                                       ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝
    
doxygen:
  extends: .schedule
  stage: analyze
  needs: ["check-image"]
  script:
    - cmake -Bbuild/Release -S. -DCMAKE_BUILD_TYPE=Release -DENABLE_MAIN=OFF -DENABLE_GUI=OFF -DENABLE_TESTING=OFF -DENABLE_DOXYGEN=ON -DWARNINGS_AS_ERRORS=OFF -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=OFF -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Release --target doxygen-docs -- -j2
  artifacts:
    untracked: true
    paths:
      - doc/html
    expire_in: 2h

coverage:
  stage: analyze
  needs: ["run-tests:gcc"]
  script:
    - mkdir -p coverage
    - lcov --gcov-tool gcov --capture --no-external --directory . --output-file coverage/coverage_all.info
    - lcov --remove coverage/coverage_all.info $(pwd)'/lib/*' $(pwd)'/test/*' --output-file coverage/coverage.info
    - genhtml coverage/coverage.info --output-directory coverage
    - lcov --list coverage/coverage.info
    - python3 tools/lcov_cobertura.py coverage/coverage.info --output coverage/cobertura-coverage.xml
  coverage: '/Total:\| ?(\d+\.?\d+\%)/'
  artifacts:
    untracked: true
    paths:
      - coverage
    expire_in: 2h
  only:
    - master

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                       Deploy                                                       ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

.pages:
  extends: .schedule
  stage: deploy
  needs: ["doxygen", "coverage"]
  script:
    - mv doc/html/ public/
    - mv coverage/ public/coverage/
  artifacts:
    name: "Documentation & Coverage Report"
    paths:
      - public
    expire_in: 7 days
    reports:
      cobertura: public/coverage/cobertura-coverage.xml
  except:
    - /^(?!master).+@/

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                    Ubuntu 20.04                                                    ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

.build:ubuntu:20.04:
  stage: build
  extends: .schedule
  image: ubuntu:20.04
  needs: []
  variables:
    DEBIAN_FRONTEND: noninteractive
    TZ: Europe/Berlin
  before_script:
    - apt update
    - apt upgrade -y
    - apt install -y build-essential clang clang-tidy cmake python3-pip ccache cppcheck qtbase5-dev
    - apt install -y gcc-10 g++-10
    - ln -sf /usr/bin/gcc-10 /usr/bin/gcc
    - ln -sf /usr/bin/g++-10 /usr/bin/g++
    - pip3 install conan
    - g++ --version
    - clang++ --version
    - clang-tidy --version
    - cmake --version
    - conan --version
    - cppcheck --version

.build:ubuntu:20.04:debug:
  extends:
    - .build:ubuntu:20.04
  script:
    - cmake -Bbuild/Debug -S. -DCMAKE_BUILD_TYPE=Debug -DENABLE_MAIN=ON -DENABLE_GUI=ON -DENABLE_TESTING=ON -DENABLE_DOXYGEN=OFF -DLOG_LEVEL=TRACE -DWARNINGS_AS_ERRORS=ON -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=ON -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Debug -- -j2
  artifacts:
    untracked: true
    expire_in: 2h

.build:ubuntu:20.04:release:
  extends:
    - .build:ubuntu:20.04
  script:
    - cmake -Bbuild/Release -S. -DCMAKE_BUILD_TYPE=Release -DENABLE_MAIN=ON -DENABLE_GUI=ON -DENABLE_TESTING=ON -DENABLE_DOXYGEN=OFF -DLOG_LEVEL=TRACE -DWARNINGS_AS_ERRORS=ON -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=ON -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Release -- -j2

ubuntu:20.04:clang:release:
  extends:
    - .build:ubuntu:20.04:release
    - .clang

ubuntu:20.04:clang:debug:
  extends:
    - .build:ubuntu:20.04:debug
    - .clang

ubuntu:20.04:gcc:release:
  extends:
    - .build:ubuntu:20.04:release
    - .gcc

ubuntu:20.04:gcc:debug:
  extends:
    - .build:ubuntu:20.04:debug
    - .gcc

.run-tests:ubuntu:20.04:
  stage: test
  extends: .schedule
  image: ubuntu:20.04
  variables:
    DEBIAN_FRONTEND: noninteractive
    TZ: Europe/Berlin
  before_script:
    - apt update
    - apt install -y cmake
    - cmake --version
  script:
    - cd build/Debug/test
    - ctest -j2 --output-on-failure

run-tests:ubuntu:20.04:clang:
  extends: .run-tests:ubuntu:20.04
  needs: ["ubuntu:20.04:clang:debug"]

run-tests:ubuntu:20.04:gcc:
  extends: .run-tests:ubuntu:20.04
  needs: ["ubuntu:20.04:gcc:debug"]

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║                                                  Arch Linux Latest                                                 ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════╝

.build:archlinux:latest:
  stage: build
  extends: .schedule
  image: archlinux:latest
  needs: []
  before_script:
    - pacman -Syyu --noconfirm --needed
    - pacman -S --noconfirm --needed base-devel cmake clang ccache cppcheck qt5-base python-pip
    - pip install conan
    - g++ --version
    - clang++ --version
    - clang-tidy --version
    - cmake --version
    - conan --version
    - cppcheck --version

.build:archlinux:latest:debug:
  extends:
    - .build:archlinux:latest
  script:
    - cmake -Bbuild/Debug -S. -DCMAKE_BUILD_TYPE=Debug -DENABLE_MAIN=ON -DENABLE_GUI=ON -DENABLE_TESTING=ON -DENABLE_DOXYGEN=OFF -DLOG_LEVEL=TRACE -DWARNINGS_AS_ERRORS=ON -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=ON -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Debug -- -j2
  artifacts:
    untracked: true
    expire_in: 2h

.build:archlinux:latest:release:
  extends:
    - .build:archlinux:latest
  script:
    - cmake -Bbuild/Release -S. -DCMAKE_BUILD_TYPE=Release -DENABLE_MAIN=ON -DENABLE_GUI=ON -DENABLE_TESTING=ON -DENABLE_DOXYGEN=OFF -DLOG_LEVEL=TRACE -DWARNINGS_AS_ERRORS=ON -DENABLE_CPPCHECK=OFF -DENABLE_CLANG_TIDY=ON -DENABLE_INCLUDE_WHAT_YOU_USE=OFF
    - cmake --build build/Release -- -j2

archlinux:latest:clang:release:
  extends:
    - .build:archlinux:latest:release
    - .clang

archlinux:latest:clang:debug:
  extends:
    - .build:archlinux:latest:debug
    - .clang

archlinux:latest:gcc:release:
  extends:
    - .build:archlinux:latest:release
    - .gcc

archlinux:latest:gcc:debug:
  extends:
    - .build:archlinux:latest:debug
    - .gcc

.run-tests:archlinux:latest:
  stage: test
  extends: .schedule
  image: archlinux:latest
  before_script:
    - pacman -Sy
    - pacman -S --noconfirm --needed cmake
    - cmake --version
  script:
    - cd build/Debug/test
    - ctest -j2 --output-on-failure

run-tests:archlinux:latest:clang:
  extends: .run-tests:archlinux:latest
  needs: ["archlinux:latest:clang:debug"]

run-tests:archlinux:latest:gcc:
  extends: .run-tests:archlinux:latest
  needs: ["archlinux:latest:gcc:debug"]